#!/usr/bin/env bash

#set -e
export ACTIVATE_SCRIPT=".venv/bin/activate"
if [ -z ${VIRTUAL_ENV+x} ]
  if [ -f ${ACTIVATE_SCRIPT} ]
  . ./.venv/bin/activate
  else
    echo "$ACTIVATE_SCRIPT not found.  Did you follow documentation to install dependencies?"
    exit 1
  fi
fi

case "$1" in
  update-users) PLAYBOOK=users.yml; ARGS=( "${@:2}"  -t update-users ) ;;
  *) PLAYBOOK=main.yml; ARGS=( "${@}" ) ;;
esac

ansible-playbook ${PLAYBOOK} "${ARGS[@]}"
